NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 999
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 999
NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 30

NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 999
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 999
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 999
NDefines.NMilitary.TRAINING_MAX_LEVEL = 2
NDefines.NMilitary.DEPLOY_TRAINING_MAX_LEVEL = 2

NDefines.NProduction.RAILWAY_GUN_MAX_MIL_FACTORIES_PER_LINE = 10
NDefines.NProduction.DEFAULT_MAX_NAV_FACTORIES_PER_LINE = 50
NDefines.NProduction.FLOATING_HARBOR_MAX_NAV_FACTORIES_PER_LINE = 50
NDefines.NProduction.CONVOY_MAX_NAV_FACTORIES_PER_LINE = 50
NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 50


NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 2
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 2
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 4

NDefines.NMilitary.EQUIPMENT_MODULE_ADD_XP_COST = 2
NDefines.NProduction.EQUIPMENT_MODULE_ADD_XP_COST = 2
NDefines.NProduction.EQUIPMENT_MODULE_REPLACE_XP_COST = 2
NDefines.NProduction.EQUIPMENT_MODULE_CONVERT_XP_COST = 2
NDefines.NProduction.EQUIPMENT_MODULE_REMOVE_XP_COST = 2

NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 30;
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 30;
NDefines.NMilitary.GARRISON_ORDER_ARMY_CAP_FACTOR = 3
NDefines.NIndustrialOrganisation.DESIGN_TEAM_CHANGE_XP_COST = 1
NDefines.NIndustrialOrganisation.ASSIGN_DESIGN_TEAM_PP_COST_PER_DAY = 0.05

NDefines.NProduction.MINIMUM_NUMBER_OF_FACTORIES_TAKEN_BY_CONSUMER_GOODS_VALUE = 0
NDefines.NProduction.MINIMUM_NUMBER_OF_FACTORIES_TAKEN_BY_CONSUMER_GOODS_PERCENT = 0

NDefines.NMilitary.WAR_SCORE_LOSSES_RATIO = 0.25;						
NDefines.NMilitary.WAR_SCORE_LOSSES_MULT_IF_CAPITULATED = 0.1;		
NDefines.NMilitary.WAR_SCORE_STRATEGIC_BOMBING_FACTOR = 0.02;  			
NDefines.NMilitary.WAR_SCORE_STRAT_BOMBING_DECAY_PER_CIVILIAN_FACTORY = 0.10;	
NDefines.NMilitary.WAR_SCORE_AIR_IC_LOSS_FACTOR = 0.08;				
NDefines.NMilitary.WAR_SCORE_LAND_DAMAGE_FACTOR = 0.1;         			
NDefines.NMilitary.WAR_SCORE_ATTACKER_AND_WINNER_FACTOR = 1.2;				
NDefines.NMilitary.WAR_SCORE_LAND_IC_LOSS_FACTOR = 0.08;         			
NDefines.NMilitary.WAR_SCORE_PROVINCE_FACTOR = 5.0;					
NDefines.NMilitary.WAR_SCORE_LEND_LEASE_GIVEN_IC_FACTOR = 0.003; 			
NDefines.NMilitary.WAR_SCORE_LEND_LEASE_RECEIVED_IC_FACTOR = 0.002;  			
NDefines.NMilitary.WAR_SCORE_LEND_LEASE_RECEIVED_FUEL_FACTOR = 0.002;		
NDefines.NMilitary.UNIT_EXPERIENCE_PER_COMBAT_HOUR = 0.0002;